### ISSUE TITLE
Exclude expired assets from search results

### ISSUE THREAD

**Issue by preetsekhon94** [Adobe-Marketing-Cloud/asset-share-commons#440] opened 2019-08-10 20:01 UTC
Hi 

I have same kind of requirement where i expired assets should not show up on landing page(home page) but when i will search them through property filter then expired assets should display with other assets.
To achieve this i have excluded expired assets from search restrictions but now the issue i am facing is that i am not even able to search them through search filter.
How should i achieve this scenario?
Will hidden filter help me out in this cas

Thanks,
Lovepreet

**Comment by davidjgonzalez** [comment] 2019-08-12 00:12
@preetsekhon94 i think this is similar to the issue raised here: https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/439#issuecomment-520272424

Basically, you want an initial search w/ some set of pre-set filters, and then you want to allow users to adjust those filters in subsequent searches - is this correct?

**Comment by preetsekhon94** [comment] 2019-08-12 04:58
Hi David,

My requirement is that expired assets should not be visible on home page and they should only be visible when we search them through property filter.

**Comment by davidjgonzalez** [comment] 2019-09-22 15:09
Closing as duplicate of #439

**Closed by davidjgonzalez** 2019-09-22 15:09 UTC
Labels: enhancement
