### ISSUE TITLE
Download model is not loading after accepting the license and its observed intermittently

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#270] opened 2018-09-12 08:13 UTC
**Describe the bug**
Download model is not loading after accepting the license and its observed intermittently when checking the developer console its throwing below JS errors
semanticui-light.js:8237 Modal: The element you specified could not be found [data-asset-share-id="license-modal"] [data-asset-share-id="license-accept"] and 
contexthub.kernel.js:4254 Uncaught TypeError: Cannot read property 'channel' of undefined

**Environment**
* AEM Version: 6..3.2
* Asset Share Commons Version: 1.5.2
* Author, Publish or both: BOTH

**To Reproduce**
1. Go to 'Home or Asset Details page'
2. Click on 'Download Action button for licensed asset'
3. Go to Developer console it will throw JS errors.
4. And intermittently Download model is not loading.

**Expected behavior**
Download model should load after accepting the license without any issue in all the time.

**Screenshots**
![image](https://user-images.githubusercontent.com/43200674/45411330-94eeef00-b691-11e8-8d2b-f92f380682dd.png)

**Additional context**
Additionally added the Developed console log here.
[license-consolelogs.log](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2374125/license-consolelogs.log)

**Comment by davidjgonzalez** [comment] 2018-09-15 17:57
Closed as a duplicate of #258

**Closed by davidjgonzalez** 2018-09-15 17:57 UTC
