### ISSUE TITLE
Assets with license property are not playing in the asset details page

### ISSUE THREAD

**Issue by assetshare2018** [Adobe-Marketing-Cloud/asset-share-commons#324] opened 2018-11-26 13:05 UTC
**Describe the bug**
Assets with the licensed property are not playing in the asset details page.

**Environment**
* AEM Version: 6.3
* Asset Share Commons Version: 1.5.2 to 1.6.8
* Author, Publish or both? both author and publish

**To Reproduce**
1. Go to default asset share commons dam path and upload video asset.
2. Add license property to the asset.
3. Open the video asset in  the asset details page
4. Video is not playing in the asset details page.

**Expected behavior**
After uploading the video asset and adding license property (`[dam:Asset]/jcr:content/metadata@xmpRights:WebStatement`) to it. it should play in the asset details page.

**Comment by davidjgonzalez** [comment] 2018-11-27 12:58
Ah yes - i *think* the way around this is for the video component to request video (probably all for simplicity) w/ the query param that indicates license agreement. We could also take a look and see how this is done in AEM Author (i assume they have to handle the same case?)

**Comment by assetshare2018** [comment] 2019-01-21 13:49
Hi,

As mentioned above, this will be made as a fix in Asset Share Commons 1.6.12.
We have tried by installing Asset Share Commons 1.6.12 as well as 1.6.10 on AEM 6.3, AEM 6.4 but the video asset having  license property(xmpRights:WebStatement) is not playing in the asset details page. 

![screenshot_324](https://user-images.githubusercontent.com/43200674/51478423-63a9cc80-1db1-11e9-92b4-2d49eee46a72.png)

**Comment by davidjgonzalez** [comment] 2019-01-21 19:51
Sorry - this was accidentally closed. This was NOT fixed in 1.6.12.

**Comment by bnayneupane** [comment] 2019-02-07 21:25
Hi David,
Appreciate to know is there is any plan to incorporate this in upcoming release?

Thank you.
Bnay

**Comment by davidjgonzalez** [comment] 2019-02-08 21:15
It looks like this is an issue with the Asset Path option is used which points to the `dam:Asset` aka `/content/dam/the-asset.mp4` rather than to a rendition `/content/dam/the-asset.mp4/jcr:content/renditions/some-rendition`.

The problem is the OOTB com.day.cq.dam.core.impl.servlet.BinaryProviderServlet handles the request for the dam:Asset and checks if the requesting user has accepted the asset by checking the user's activity stream. This is a preview, so its very reasonable a user has not accepted anything at this point. 

I think we'll have to stew on a solution, since there isnt a clear way around this Servlet - howver in the interim you can specify the original (or whichever rendition is best for preview) directly in the component, like so: 

![image](https://user-images.githubusercontent.com/1451868/52506438-97139600-2bbc-11e9-8917-ec5ad001dcd6.png)

Hitting the rendition directly bypasses the DRM check, allowing the asset to be served up.

**Comment by bnayneupane** [comment] 2019-02-13 00:21
Hi David 
Many thanks - I will proceed as suggested and will come back if any further questions. 

Thank you.
Bnay

**Comment by assetshare2018** [comment] 2019-02-19 11:21
Hi David,

We have tried the solution provided above, it works fine for .mp4 and .mov. Still the videos with the below formats are not playing:

.mpg
.wmv
.aif
.swf

Could you please let us know the ETA.

**Comment by davidjgonzalez** [comment] 2019-02-19 14:24
@assetshare2018 im not sure the best way around this - the OOTB BinaryServlet does hard checks against the activity stream. 

Perhaps this could be part of https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/345 ... but IDK. It seems like that dam:Asset's servlet cannot be invoked for this functionality as that will block out.

So, no ETA at this time. Have you tried the suggested work-around above?

**Comment by assetshare2018** [comment] 2019-02-21 05:57
@davidjgonzalez Yes, we tried the work-around suggested above and it works well for .mp4 and .mov format but still we are facing the issue with ".mpg, .wmv, .aif, .swf".

**Comment by assetshare2018** [comment] 2019-04-01 08:53
@davidjgonzalez Could you please let us know the ETA for this issue.

**Comment by davidjgonzalez** [comment] 2019-04-01 20:59
No ETA, sorry.

I’m a bit bewildered that using the original workaround works for mp4 and mov, but not the other formats; doesn’t make sense assuming they are infact requesting the original rendition resource directly

**Comment by davidjgonzalez** [comment] 2020-03-13 02:58
This should be fixed via the Asset Renditions framework and the updated Details - Image component in 1.9.x+ .
Make sure you arent using Legacy mode in the component.

**Closed by davidjgonzalez** 2020-03-13 02:58 UTC
Labels: bug

**Comment by anuragsengupta7** [comment] 2021-07-05 15:28
We are using asset share commons 1.9.4 for AEM 6.5 and still facing the exact issue, videos with copyright URL not playing in asset details page.
Moreover, the workaround with Original rendition is not working for me as well.
@davidjgonzalez @bnayneupane any clue how to resolve this.
<img width="682" alt="video" src="https://user-images.githubusercontent.com/86973375/124493737-9a35ff00-ddd3-11eb-89f8-b42e7966673b.PNG">

**Comment by davidjgonzalez** [comment] 2022-05-05 12:38
@anuragsengupta7 are you using the Legacy rendition mode? What is the URL being printed out in the `<video src=".."` attribute?
