### ISSUE TITLE
Sorting not working in the copied URL

### ISSUE THREAD

**Issue by itzmuthu** [Adobe-Marketing-Cloud/asset-share-commons#390] opened 2019-03-20 19:27 UTC
**Describe the bug**
Sorting not working in the copied URL

**Environment**
* AEM Version:  AEM 6.4.2
* Asset Share Commons Version: 1.6.12
* Author, Publish or both? both

**To Reproduce**
- got to http://localhost:4503/content/asset-share-commons/en/light.html in chrome browser
- select sorting as size and order is DESC. now the URL will look like http://localhost:4503/content/asset-share-commons/en/light.html?orderby=%40jcr%3Acontent%2Fmetadata%2Fdam%3Asize&layout=card&p.offset=0&p.limit=24
- copy the URL to new tab now the URL will look like http://localhost:4503/content/asset-share-commons/en/light.html?orderby=%40jcr%3Acontent%2Fmetadata%2Fdam%3Asize&layout=card&p.offset=0&p.limit=24
- keep the sort field as it is i.e. size and change the DESC to ASC. now the url change as http://localhost:4503/content/asset-share-commons/en/light.html?orderby.sort=asc&layout=card&p.offset=0&p.limit=24
- now again change sort type as DESC. now URL look like  http://localhost:4503/content/asset-share-commons/en/light.html?orderby.sort=desc&layout=card&p.offset=0&p.limit=24    the result are not same as initial sort by Size and order DESC 
[SortIssue.docx](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2989774/SortIssue.docx)

**Screenshots**
refer attached doc for steps to reproduce this issue

**Additional context**
[SortIssue.docx](https://github.com/Adobe-Marketing-Cloud/asset-share-commons/files/2989777/SortIssue.docx)

**Comment by davidjgonzalez** [comment] 2019-03-24 16:48
It looks like when the Sort order is selected here, the "orderby" property falls off.

**Comment by davidjgonzalez** [comment] 2019-03-25 16:44
@itzmuthu fixed via #394 -- thanks for the issue and great description/how to reproduce! Makes identifying and thus fixing the issue so much easier!! 👍

**Closed** 2019-06-16 21:04 UTC
Labels: bug
