### ISSUE TITLE
Date range upper bound should be inclusive

### ISSUE THREAD

**Issue by mrozati** [Adobe-Marketing-Cloud/asset-share-commons#378] opened 2019-02-25 14:11 UTC
**Situation**
The date range filter currently evaluates dates at 12:00AM of the selected day. While this makes sense for the lower bound date, it causes confusions with the upper bound date because it practically doesn't include that date. IMHO it is very common that upper bound date is including.

**Evaluate upper bound date at 12:59PM**
We should evaluate the upper bound date at 12:59:59PM. Alternatively we could add +1 day to the selected upper bound date.
Optionally we could make this configurable for admin or editor (something like "include upper date in range"). The default should be "includeUpperDate=true"

**Comment by davidjgonzalez** [comment] 2019-02-26 00:26
Duplicate of https://github.com/Adobe-Marketing-Cloud/asset-share-commons/issues/39

Closing #39

**Closed** 2019-03-13 00:20 UTC
Labels: bug
