### ISSUE TITLE
Removal of for "generic" Sort By and Sort Direction labels

### ISSUE THREAD

**Issue by juliaetate** [Adobe-Marketing-Cloud/asset-share-commons#297] opened 2018-10-02 19:14 UTC
**Describe the bug**
I just updated to 1.6.6 to resolve a found issue with the tagging overlaps, and I noticed that the generic Sort By and Sort Direction were removed, which I do like. Unfortunately, on my site, I've had to set up my files to sort by Title rather than one of the available options. As a result of removing Sort By, I now see Unknown on load. Is there a reason why Title can't be included in the sort options or another way I can get a default label rather than Unknown?

**Environment**
* AEM Version: 6.3.3
* Asset Share Commons Version: 1.6.6
* Author, Publish or both? Both

**To Reproduce**
1. Go to Assets list page.
2. Scroll down to Sort drop downs.
4. When using custom sort order, set to Title, without Sort By default, Unknown is displayed.

**Expected behavior**
I would like to see Title or be able to add a default like what was removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/18601409/46371225-6a1f0780-c64d-11e8-95af-4c7da9a122fe.png)

**Comment by davidjgonzalez** [comment] 2018-10-02 20:28
Hi @juliaetate - a quick fix would be to add the Title property to the Sort component's list of options (and make sure it maps to the property selected as Default Sort By in the Results component) ...

It seems a bit odd that you'd start with a default sort that you can't get back to after changing the sort? Maybe im missing something?  

The problem is the sortable properties dont have any real "natural" labels (theyre just ordered JCR properties in the damAssetLucene index), so you have to specify them in the components... If this it's a compelling use case, we could look to add a "Sort By Label" in the Results so you could add it there.. but it seems rather odd to me you wouldnt want to make the default available in the dropdown as well.

Let me know what you think!

**Comment by davidjgonzalez** [comment] 2018-10-04 05:55
@juliaetate any thoughts on this?

**Comment by juliaetate** [comment] 2018-10-26 17:57
My default sort has been added to the drop down. The problem is that on load, it shows as Unknown on load because it's not automatically mapped. In the previous version, it would show Sort which prevented this issue, but the update changed it to show just from what it could map to from the initial options provided in Asset Share Commons. 

![image](https://user-images.githubusercontent.com/18601409/47583982-8c3f3900-d91e-11e8-96bc-a31313962fd8.png)

**Comment by davidjgonzalez** [comment] 2018-10-30 16:09
@juliaetate did you have a chance to review this? We are planning on releasing 1.6.10 tomorrow AM - ideally, if this is an issue, we'd get a fix out for it.

**Comment by juliaetate** [comment] 2018-11-14 15:03
@davidjgonzalez I've modified my default search to use Title, which isn't an option that has been provided. Is there a reason that Title isn't available from programming?

**Comment by davidjgonzalez** [comment] 2018-11-14 16:25
Only properties marked as Orderable in the damAssetLucene index are exposed in the drop-down. This is to prevent you from picking slow properties and incurring unexpected performance issues at scale. If you want to sort on a property, it should be marked as Orderable - which may require you to talk to your Dev/Ops team.

**Comment by juliaetate** [comment] 2018-12-10 17:05
@davidjgonzalez Sorry for the delayed response. I can't pick an unorderable property from the Results component, but I have to sort my assets in alphabetical order for my requirements. I just don't have a way to stop the default from showing Unknown. Thanks so much for adding an option that will prevent this! I'm excited to get the next update!

**Closed** 2019-01-11 22:44 UTC
Labels: enhancement
