### ISSUE TITLE
Search results are not sustaining second time after navigating back to home page from detail page 

### ISSUE THREAD

**Issue by anoopkumargarg** [Adobe-Marketing-Cloud/asset-share-commons#233] opened 2018-08-16 08:18 UTC
**Describe the bug**
Search results are not sustaining second time after navigating back to home page from detail page 

**Environment**
* AEM Version: 6.3 + SP2
* Asset Share Commons Version: 1.5.2
* Author, Publish or both: Both

**To Reproduce**
Open Asset share page http://localhost:4502/content/asset-share-commons/en/light.html
Search some asset like "Sample"
You will get few assets in search results
Click on first asset and navigate to detail page
Come back to asset share home page using back button available on detail page 
Search results are persisting
Now click on second asset and navigate to detail page
Come back to asset share home page using back button available on detail page 
Search results are NOT persisting

**Expected behavior**
Search results should persist after coming back from detail page for second time as well

**Screenshots**

**Additional context**

**Comment by godanny86** [comment] 2018-08-16 13:41
Thanks for openeing @anoopkumargarg . The way the "Back" button works is a returnUrl property is persisted to local browser storage. On the 2nd back navigation, the returnUrl is overwritten without the original search query parameters.

**Comment by godanny86** [comment] 2018-08-16 13:45
![image](https://user-images.githubusercontent.com/8974514/44212281-ed85a780-a138-11e8-9760-565cd96ad031.png)

Navigate to asset details page and return:
![image](https://user-images.githubusercontent.com/8974514/44212360-23c32700-a139-11e8-94bc-fa1b5fef94d4.png)

**Comment by davidjgonzalez** [comment] 2018-10-31 13:43
@anoopkumargarg are you still experiencing this issue?

**Comment by davidjgonzalez** [comment] 2018-11-29 22:10
Closing due to lack of info. Please re-open with info on how to reproduce.

**Closed by davidjgonzalez** 2018-11-29 22:10 UTC
Labels: bug, needs more info
