### ISSUE TITLE
Stacktraces logged in error.og if Email Service is not configured

### ISSUE THREAD

**Issue by chinny-biztech** [Adobe-Marketing-Cloud/asset-share-commons#48] opened 2017-11-09 00:13 UTC
Stacktraces in logs if OPTIONAL -ACS AEM Commons 3.11.0 is not installed or Email Service is not configured.

```
Caused   by: java.lang.ClassNotFoundException:   com.adobe.acs.commons.email.EmailService not found by   com.adobe.aem.commons.assetshare.core [520]
--
at   org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
at   org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
at   org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
at   java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 133 common frames omitted
 
09.11.2017 11:05:41.947 *WARN*   [OsgiInstallerImpl] com.adobe.aem.commons.assetshare.core   [com.adobe.aem.commons.assetshare.components.actions.share.impl.EmailShareServiceImpl(5806)]   Failure loooking up field assetDetailsResolver in class class com.adobe.aem.commons.assetshare.components.actions.share.impl.EmailShareServiceImpl.   Assuming no such field. (java.lang.NoClassDefFoundError:   Lcom/adobe/acs/commons/email/EmailService;)
java.lang.NoClassDefFoundError:   Lcom/adobe/acs/commons/email/EmailService;
at   java.lang.Class.getDeclaredFields0(Native Method)
at   java.lang.Class.privateGetDeclaredFields(Class.java:2583)
at   java.lang.Class.getDeclaredField(Class.java:2068)
at   org.apache.felix.scr.impl.inject.FieldHandler.getField(FieldHandler.java:222)
at   org.apache.felix.scr.impl.inject.FieldHandler.findField(FieldHandler.java:159)
at   org.apache.felix.scr.impl.inject.FieldHandler.access$400(FieldHandler.java:51)
at   org.apache.felix.scr.impl.inject.FieldHandler$NotResolved.resolve(FieldHandler.java:838)
at   org.apache.felix.scr.impl.inject.FieldHandler$NotResolved.fieldExists(FieldHandler.java:864)
at   org.apache.felix.scr.impl.inject.FieldHandler.fieldExists(FieldHandler.java:918)
at   org.apache.felix.scr.impl.inject.FieldHandler$ReferenceMethodImpl.getServiceObject(FieldHandler.java:982)
at   org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201)
at   org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.prebind(DependencyManager.java:1118)
at   org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1520)
at   org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1006)
at   org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859)
at   org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823)
at   org.apache.felix.framework.ServiceRegistrationImpl.getFactoryUnchecked(ServiceRegistrationImpl.java:347)
at   org.apache.felix.framework.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:247)
at   org.apache.felix.framework.ServiceRegistry.getService(ServiceRegistry.java:344)
at   org.apache.felix.framework.Felix.getService(Felix.java:3700)
at   org.apache.felix.framework.BundleContextImpl.getService(BundleCont
```

**Comment by davidjgonzalez** [comment] 2017-11-09 03:47
Duplicate of #29 - Please see #29 for details.

**Closed by davidjgonzalez** 2017-11-09 03:47 UTC
Labels: duplicate

**Comment by davidjgonzalez** [comment] 2017-11-09 04:02
FYI - opened a PR for #29 with a fix (assuming it passes review)

**Comment by chinny-biztech** [comment] 2017-11-09 04:31
Ok no worries. thanks.
